# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Country(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, country_code: str=None):  # noqa: E501
        """Country - a model defined in Swagger

        :param country_code: The country_code of this Country.  # noqa: E501
        :type country_code: str
        """
        self.swagger_types = {
            'country_code': str
        }

        self.attribute_map = {
            'country_code': 'countryCode'
        }
        self._country_code = country_code

    @classmethod
    def from_dict(cls, dikt) -> 'Country':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Country of this Country.  # noqa: E501
        :rtype: Country
        """
        return util.deserialize_model(dikt, cls)

    @property
    def country_code(self) -> str:
        """Gets the country_code of this Country.


        :return: The country_code of this Country.
        :rtype: str
        """
        return self._country_code

    @country_code.setter
    def country_code(self, country_code: str):
        """Sets the country_code of this Country.


        :param country_code: The country_code of this Country.
        :type country_code: str
        """

        self._country_code = country_code
